# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request!
  We have detected this is the first time for you to contribute
  to *QSIPrep*.
  Please check out our [contributing guidelines](https://github.com/pennlinc/qsiprep/blob/master/CONTRIBUTING.md).

  These are guidelines intended to make communication easier by describing a
  consistent process, but don't worry if you don't get it everything exactly
  "right" on the first try.

  We invite you to list yourself as a *QSIPrep* contributor, so if your name
  is not already mentioned, please modify the
  [``CITATION.cff``](https://github.com/pennlinc/qsiprep/blob/master/CITATION.cff)
  file with your data. If you do so, your name will be listed as an author
  at the next release. Please add yourself to the list in alphabetical order,
  keeping Cieslak, Matthew as first and Satterthwaite, Theodore D. as last
  authors, e.g.:

  ```
  ...
  authors:
    ...
    - family-names: <LastName>
      given-names: <FirstName>
      affiliation: <Affiliation>
      orcid: <Id>
    ...
  ...
  ```

  Of course, if you want to opt out this time there is no
  problem at all with adding your name later.
  You will be always welcome to add it in the future whenever
  you feel it should be listed.
